name: Build and Deploy to GitHub Pages

on:
  workflow_call:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build Tailwind CSS (if present)
        run: npm run build-css
        continue-on-error: true

      - name: Build Next.js
        run: npm run build

      - name: Export static site (next export -> out)
        run: |
          # next export works only if your app is configured for static export.
          # We'll run it and continue if it fails so deployment can still attempt.
          npx next export -o out || true

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
