name: Build, Release and Deploy Unified Workflow
on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  # Build job
  build:
    uses: steve-kaschimer/steve-kaschimer.github.io/.github/workflows/build_nexts.yaml@main
                
  release:
    needs: build
    uses: steve-kaschimer/steve-kaschimer.github.io/.github/workflows/release.yaml@main
    with:
      GITHUB_TOKEN: ${{env.GITHUB_TOKEN)}      
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    
  deploy:
    needs: release
    uses: steve-kaschimer/steve-kaschimer.github.io/.github/workflows/deploy_nextjs.yaml@main
