name: Build, Release and Deploy Unified Workflow
on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    uses: https://github.com/steve-kaschimer/steve-kaschimer.github.io/.github/workflows/buildnexs.yaml@main
                
  release:
    needs: build
    uses: https://github.com/steve-kaschimer/steve-kaschimer.github.io/.github/workflows/release.yaml@main
    
  deploy:
    needs: release
    uses: https://github.com/steve-kaschimer/steve-kaschimer.github.io/.github/workflows/deploy_nextjs.yaml@main
