name: Build and Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next

      - name: Install dependencies
        run: npm ci

      - name: Build Tailwind CSS (if present)
        run: npm run build-css
        continue-on-error: true

      - name: Build Next.js
        run: npm run build

      - name: Verify static export output
        run: |
          # Newer Next.js versions removed `next export` in favor of setting `output: 'export'` in next.config.js.
          # `next build` will produce a static `out/` directory when that setting is used.
          echo "Checking for ./out directory produced by next build..."
          if [ -d "./out" ]; then
            echo "Found ./out - ready to upload"
            ls -la ./out | sed -n '1,200p'
            exit 0
          fi
          echo "ERROR: ./out directory not found."
          echo "If you want a static export, set `output: 'export'` in next.config.js (see https://nextjs.org/docs/app/building-your-application/deploying/static-exports)."
          echo "Alternatively deploy to a platform that supports server-side Next.js (Vercel, Netlify, etc.)."
          exit 1

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
