name: Build, Release and Deploy Unified Workflow
on:
  push:
    branches:
      - main
      - release**

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write
  attestations: write

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  # versioning
  version:
    uses: steve-kaschimer/workflow-core-ci/.github/workflows/core-ci.yml@main

  # validation
  validate:
    needs: version
    uses: steve-kaschimer/steve-kaschimer.github.io/.github/workflows/workflow-validate-issue-attached.yml@main
  
  # Build job
  build:
    needs: validate
    uses: steve-kaschimer/steve-kaschimer.github.io/.github/workflows/build_nexts.yaml@main

  # release job
  release:
    needs: build
    uses: steve-kaschimer/steve-kaschimer.github.io/.github/workflows/release.yaml@main

  # deploy job
  deploy:
    if: ${{ startsWith(github.ref_name, 'release') }}
    needs: release
    uses: steve-kaschimer/steve-kaschimer.github.io/.github/workflows/deploy_nextjs.yaml@main
